export const DATABASE_ID=process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID=process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const IMAGES_BUCKET_ID=process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
export const MEMBERS_ID=process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID=process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;

export const TASKS_ID=process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const TASK_ATTACHMENTS_ID=process.env.NEXT_PUBLIC_APPWRITE_TASK_ATTACHMENTS_ID!;
export const ATTACHMENT_COMMENTS_ID=process.env.NEXT_PUBLIC_APPWRITE_ATTACHMENT_COMMENTS_ID!;
